// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2VSQ05LX9FP8oZQhEt1tO3hUp_0SxoQk',
    appId: '1:243939484600:web:21f75c6d68f42bab93254d',
    messagingSenderId: '243939484600',
    projectId: 'grocery-vegetable-market-215f9',
    authDomain: 'grocery-vegetable-market-215f9.firebaseapp.com',
    storageBucket: 'grocery-vegetable-market-215f9.appspot.com',
    measurementId: 'G-K1V6V408YP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAag9sX1VGnL013PEpLuLil403KbmkqejI',
    appId: '1:243939484600:android:eaf2123b83cece2093254d',
    messagingSenderId: '243939484600',
    projectId: 'grocery-vegetable-market-215f9',
    storageBucket: 'grocery-vegetable-market-215f9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeiSJCAfqVoddv2d4xdxVOGMauCwar60w',
    appId: '1:243939484600:ios:15de4e23741701a993254d',
    messagingSenderId: '243939484600',
    projectId: 'grocery-vegetable-market-215f9',
    storageBucket: 'grocery-vegetable-market-215f9.appspot.com',
    iosClientId: '243939484600-5n6960ja1a2ke5iplf4qfvelh03i9qep.apps.googleusercontent.com',
    iosBundleId: 'com.example.groceryVegitableMarket',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeiSJCAfqVoddv2d4xdxVOGMauCwar60w',
    appId: '1:243939484600:ios:15de4e23741701a993254d',
    messagingSenderId: '243939484600',
    projectId: 'grocery-vegetable-market-215f9',
    storageBucket: 'grocery-vegetable-market-215f9.appspot.com',
    iosClientId: '243939484600-5n6960ja1a2ke5iplf4qfvelh03i9qep.apps.googleusercontent.com',
    iosBundleId: 'com.example.groceryVegitableMarket',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2VSQ05LX9FP8oZQhEt1tO3hUp_0SxoQk',
    appId: '1:243939484600:web:376b6533cf09926b93254d',
    messagingSenderId: '243939484600',
    projectId: 'grocery-vegetable-market-215f9',
    authDomain: 'grocery-vegetable-market-215f9.firebaseapp.com',
    storageBucket: 'grocery-vegetable-market-215f9.appspot.com',
    measurementId: 'G-5V2EB66DPE',
  );
}
